
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int ID = 2;
  public static final int STRING = 3;
  public static final int error = 1;
  public static final int ADD = 4;
  public static final int DELETE = 6;
  public static final int SHOW = 5;
  public static final int UPDATE = 7;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "STRING",
  "ADD",
  "SHOW",
  "DELETE",
  "UPDATE"
  };
}

